include ./nord.conf
# include ./tokyo.conf

allow_remote_control yes

# cosmetics
hide_window_decorations no
shell_integration no-cursor

adjust_line_height  110%
adjust_column_width 100%
window_padding_width 4 2  4 12
underline_hyperlinks always

# tab bar 
tab_bar_edge bottom
tab_bar_style custom

bell_on_tab "🔔 "
tab_bar_min_tabs 1
tab_switch_strategy left

tab_bar_background #2E3440
inactive_tab_background #3B4252
inactive_tab_foreground #D8DEE9
active_tab_background #88C0D0
active_tab_foreground #2E3440
active_tab_font_style bold
tab_bar_style powerline
tab_powerline_style round


# keybindings 
macos_option_as_alt yes

map ctrl+n no_op

map cmd+w close_tab 
map ctrl+shift+w close_window
map cmd+shift+w close_window 
map ctrl+w no_op

map cmd+shift+q close_os_window
map ctrl+alt+t set_tab_title

map cmd+, no_op

# splits
enabled_layouts splits

map ctrl+e>s launch --location=hsplit
map ctrl+e>v launch --location=vsplit
map ctrl+shift+enter launch --location=split
map ctrl+e>r layout_action rotate

map ctrl+e>h neighboring_window left
map ctrl+e>l neighboring_window right
map ctrl+e>k neighboring_window up
map ctrl+e>j neighboring_window down

map ctrl+e>shift+h move_window left
map ctrl+e>shift+l move_window right
map ctrl+e>shift+k move_window up
map ctrl+e>shift+j move_window down

map ctrl+e>- resize_window shorter 
map ctrl+e>= resize_window taller 
map ctrl+e>, resize_window narrower 
map ctrl+e> resize_window wider 3
map ctrl+e>b resize_window reset

# BEGIN_KITTY_FONTS
font_family      family="Gintronic"
symbol_map U+E000-U+F8FF Symbols Nerd Font Mono
symbol_map U+F0000-U+FFFFF Symbols Nerd Font Mono  
symbol_map U+100000-U+10FFFF Symbols Nerd Font Mono
font_size 13.5
# END_KITTY_FONTS
